name: labo1
channels:
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - scipy
  - pytest
  - mkdocs
  - mkdocs-material
  - mkdocstrings
  - mkdocstrings-python
  - black
  - jupyter
  - pip
  - pip:
    - mkdocs-jupyter  # conda version is missing assets
    - -e .
