[project]
name = "labo1"
version = "2.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [
  { name = "Mauro Silberberg", email = "maurosilber@gmail.com" },
]
keywords = []
classifiers = [
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
]
dependencies = [
  "matplotlib",
  "numpy",
  "scipy",
]

[project.urls]
documentation = "https://maurosilber.github.io/labo1"
homepage = "https://github.com/maurosilber/labo1"
issues = "https://github.com/maurosilber/labo1/issues"

[build-system]
requires = ["uv_build>=0.9,<0.10"]
build-backend = "uv_build"

[tool.pyrefly]
python-interpreter-path = ".pixi/envs/default/bin/python"
project-excludes = [".pixi", "**/__pycache__"]

[tool.pyright]
typeCheckingMode = "standard"
venv = "default"
venvPath = ".pixi/envs/"

[tool.pytest.ini_options]
addopts = "--import-mode=importlib"
pythonpath = "."

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.per-file-ignores]
"docs/**" = ["B018"]  # useless expressions (last expression in cells)

[tool.tombi]
toml-version = "v1.1.0"
